Repository YorCreative/Laravel-UrlShortener, pull requests merged in 2022-08, with the labels that each got.

#1 Github Action Addition
  .github/workflows/phpunit.yml
  composer.json
  composer.lock
  tests/TestCase.php
Labels: enhancement

#2 Github Action Update
  .github/workflows/phpunit.yml
Labels: enhancement

#3 MIT License
  LICENSE
Labels: documentation

#4 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#5 Service Provider Auto Discovery
  composer.json
Labels: bug

#6 README Shield Badges
  README.md
Labels: documentation

#8 phpunit.xml update
  composer.lock
  phpunit.xml
  src/Services/UtilityService.php
  src/Utility/Config/urlshortener.php
Labels: bug

#9 Typo
  README.md
Labels: documentation

#10 Composer License
  composer.json
  composer.lock
Labels: documentation
